### ISSUE TITLE
Auto KOL - Twitter login problem

### ISSUE THREAD

**Issue by jfrank-summit** [autonomys/autonomys-agents#62]
@Xm0onh is unable to login via username/password flow. See comment [here](https://github.com/autonomys/autonomys-agents/pull/59#discussion_r1887616449)

```
  return { status: 'error', err: new Error(await res.text()) };                                     ^


Error: {"errors":[{"code":366,"message":"Missing data. g;173438488056892411:-1734384880624:p5xV73kyHCpDTRMWGc0hwXHR:8"}]}
    at TwitterUserAuth.executeFlowTask (auth-user.ts:359:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TwitterUserAuth.handleAcid (auth-user.ts:304:12)
    at TwitterUserAuth.login (auth-user.ts:111:16)
    at ExtendedScraper.login (scraper.ts:655:5)
    at ExtendedScraper.initialize (api.ts:42:13)
    at Function.getInstance (api.ts:18:13)
    at <anonymous> (twitter.ts:10:24)
```

**Comment by jfrank-summit** [comment]
Have not seen this issue again, closing.
